#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ports:
      - "9210:9200"
      - "9310:9300"
  nimbus:
    image: storm:1.0.3
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - "6627:6627"
  supervisor:
    image: storm:1.0.3
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
      - elasticsearch
      - kafka
    links:
      - nimbus
      - zookeeper
      - elasticsearch
      - kafka
    restart: always
  storm-ui:
    image: storm:1.0.3
    container_name: storm-ui
    command: storm ui
    depends_on:
      - nimbus
    ports:
      - "8080:8080"
      - "8000:8000"
  hbase:
    build:
      context: ../../images/hbase
      args:
        HBASE_VERSION: $HBASE_VERSION
    container_name: hbase
    ports:
      - "16010:16010"
    depends_on:
      - zookeeper
    volumes:
      - "/hbase"
  metron:
    build:
      context: ../../images/metron
      args:
        METRON_VERSION: $METRON_VERSION
        STORM_VERSION: $STORM_VERSION
        HBASE_VERSION: $HBASE_VERSION
    container_name: metron
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
    volumes_from:
      - hbase
